### ISSUE TITLE
Albert, Dave, Josh BOOKCLUB!!!

### ISSUE THREAD

**Issue by jnpearson4850** [ga-dc/project3-gallery#114]
Link to repo: 
https://github.com/DaveSchuetz/BookClub-BackEnd

Link to deployed app:
https://mern-bookclub.herokuapp.com/ (BACK-END)
Font-End coming very soon/ 

Things you'd like specific feedback on:
Search controller and React Search component. Feel like that was a major highlight and if there is anyway to improve.

**Comment by DaveSchuetz** [comment]
http://mern-bookclub.surge.sh/
https://github.com/DaveSchuetz/BookClub-FrontEnd

Here is our front-end

**Comment by jnpearson4850** [comment]
Awesome. What do I need to do to get the styling back? just go through the
Git repo on you page?
