### ISSUE TITLE
Group 7 - Submission 

### ISSUE THREAD

**Issue by SeanTay** [ga-dc/project3-gallery#22]
Deployed at: https://seantay.github.io/datingapp-angular/

login as: bob@example.com
password: pizzajammy

Sign up with not working.  

Repo at 
https://github.com/SeanTay/datingapp-angular
https://github.com/SeanTay/datingapp-rails

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/SeanTay/datingapp-angular/pull/7)
