### ISSUE TITLE
FeedMe - GA WDI-12 Project 3 By Group 8: Michael Lai, Mark Sweet, Mike Rubin

### ISSUE THREAD

**Issue by merubin** [ga-dc/project3-gallery#30]
## **Main Project Repo:**
https://github.com/MichaelZLai/FeedMe

## Deployment.
  Both the back-end and front-end have been fully deployed.  Each individual contributor has their own deployment site. The following are the deployment locations and URL's fore each contributor:

|Contributor  | Front-end Repo | Front-end Host URL | Back-end Repo | Back-end Host URL |
| ----------- | :------------- | :---------- | :------------ | :----------------- |  
|**Michael Lai**| https://github.com/MichaelZLai/FeedMe-FE | https://michaelzlai.github.io/FeedMe-FE/#/feedme |  https://github.com/MichaelZLai/FeedMe-BE|  https://feedme-be.herokuapp.com/
|**Mark Sweet**|  https://github.com/marks828/project3_angular | https://marks828.github.io/#/feedme |  https://github.com/marks828/project3 | https://feedmerails.herokuapp.com/
|**Mike Rubin**| https://github.com/merubin/feedmefe |https://merubin.github.io/feedmefe/#/feedme  |  https://github.com/merubin/yelp |  https://yelp-backend-rails.herokuapp.com/

**Comment by jshawl** [comment]
👍 Excellent job on project 3! Take a look at my feedback https://gist.github.com/jshawl/af9599340ec3523726aa4c175afc7a28 and let me know if you have any questions.

We'll find a time to meet together about this this week.

**Comment by jshawl** [comment]
@marks828 @michaelzlai
