### ISSUE TITLE
Aceso-Group 1

### ISSUE THREAD

**Issue by griffind2009** [ga-dc/project3-gallery#31]
Angelo, Domonique, Poh

Front end: https://griffind2009.github.io/Doctor_App_Angular/#/doctors
Firebase: https://aceso-3b639.firebaseapp.com/#/doctors
Back end: https://aceso-app.herokuapp.com/doctors

github repos: https://github.com/griffind2009/Doctor_App_Angular
                       https://github.com/griffind2009/Doctor_app

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/griffind2009/Doctor_App_Angular/pull/11)
