### ISSUE TITLE
project 3 NDA

### ISSUE THREAD

**Issue by brophy2321** [ga-dc/project3-gallery#33]
https://github.com/brophy2321/Project-3

**Comment by brophy2321** [comment]
https://brophy2321.github.io/Project-3-Angular/
https://gentle-woodland-78232.herokuapp.com/

**Comment by brophy2321** [comment]
we deployed it to github pages but its not coming up

**Comment by jshawl** [comment]
👍 Nice job on project 3! Take a look at my feedback and let me know if you have any questions - https://gist.github.com/jshawl/774824c0068fd847fe69a8a093dd8aa1

I'll find a time for us to meet this week about the project.
