### ISSUE TITLE
Project 3 --- Group 4

### ISSUE THREAD

**Issue by marlungu** [ga-dc/project3-gallery#34]
Mariana, Billy, and Alex

Front-end: http://marianalungu.io/globeView_angular/#/passports
Back-end: https://globalcitizen.herokuapp.com/

github repos:
                    https://github.com/marlungu/globeView_angular
                    https://github.com/marlungu/globeView

**Comment by amaseda** [comment]
Here are some PRs to your front- and back-end apps. **Do not merge them, just read through my code comments.**
