### ISSUE TITLE
Group 7 - Taylor, Sam, Bedig, Malcolm

### ISSUE THREAD

**Issue by taylorscott91** [ga-dc/project3-gallery#46]
https://github.com/ga-wdi-exercises/project3/issues/413

We're using Hab's idea as a basis to build an anonymous message board, with an array of subtopic boards and easy submission. Users can create new topics, post on those topics, and customize their usernames. We're planning on having a very clean and simple interface. 
MVP: CR(UD optional), good styling. 
Silver: Update/Delete (for your own posts?), implementing markdown in posts, file uploads
Gold: customizable color themes

**Comment by superbuggy** [comment]
👍 Nice! After deciding on your git workflow and team roles, build your ERDs.
