### ISSUE TITLE
Group 3: GABook (Adam, Mike, Aaron, Dominick)

### ISSUE THREAD

**Issue by ghost** [ga-dc/project3-gallery#53]
Planning Repo
https://github.com/maikelnabil/gabook-planning

Front-End
Deployed: https://nairul.github.io/gabook-frontend/
Repo: https://github.com/nairul/gabook-frontend

Back-End
Deployed Back-End: https://gabook.herokuapp.com/profiles.json
Back-End Repo: https://github.com/maikelnabil/gabook-backend

**Comment by avalant** [comment]
Feedback left in garnet.
