### ISSUE TITLE
Sam, Taylor, Bedig, Mal Group -Project 3

### ISSUE THREAD

**Issue by sdkclements** [ga-dc/project3-gallery#56]
<h4> oneShot </h4>
<img src="http://i.imgur.com/BI3SQrL.png" alt="Drawing" style="width: 200px;"/>

<hr>
<h3><em> <i> Front End  </i> </em></h3>
<hr><br>
<b> Hosting:  https://sdkclements.github.io/oneShotFront/#/ </b> <br>
<b> Repository:  https://github.com/sdkclements/oneShotFront </b> <br>
<hr>
<br>
<h3><em> <i> Back End  </i> </em><br></h3>
<hr>
<b> Hosting: https://one-shot-backend.herokuapp.com/ </b><br>
<b> Repository: https://github.com/sdkclements/oneShotBackend</b><br>
<hr>
 <i> Main Readme on the Front end </i>

**Comment by superbuggy** [comment]
see PR for comments!
