### ISSUE TITLE
Ammar, Erin, Ick - WeaTro

### ISSUE THREAD

**Issue by kwonih1020** [ga-dc/project3-gallery#68]
Deployed remote server link: https://infinite-escarpment-36437.herokuapp.com/stations

Deployed app link: http://www.erinedawson.com/weatro/#/stations

GitHub repo: https://github.com/edawson1980/weatro

**Comment by juancgarcia** [comment]
Good job team 👍! please refer to the Pull Request on your project's repo for feedback:
edawson1980/weatro#1

@edawson1980 @ammaralasadi1 @kwonih1020
