### ISSUE TITLE
Animal Adoption - Curtis, Andres, Luisa 

### ISSUE THREAD

**Issue by Costle784** [ga-dc/project3-gallery#71]
deployed rails API: https://animaladoption.herokuapp.com/
deployed app:  https://costle784.github.io/Animal-adoption/
project repo: https://github.com/Costle784/Animal-adoption

**Comment by juancgarcia** [comment]
Good job team 👍! please refer to the Pull Request on your project's repo for feedback:
Costle784/Animal-adoption#11

@Costle784 @lgmusic24 @andresmaria
