### ISSUE TITLE
Group 2: Charles, Frew, Kendall

### ISSUE THREAD

**Issue by kadkins4** [ga-dc/project3-gallery#77]
Project Ideas:

1. Twitter - Picture
2. Parking Locations
3. Angular to English

**Comment by kadkins4** [comment]
![img_1173](https://user-images.githubusercontent.com/27822197/29465579-c4887dde-8407-11e7-9cc7-23cc543b856a.JPG)


planning has begun for 'tweet-flick' working title

**Comment by kadkins4** [comment]
![img_1174](https://user-images.githubusercontent.com/27822197/29465958-11c0180e-8409-11e7-9525-3d3b1fe53100.JPG)

MVP through ALLSTAR

**Comment by cwcox** [comment]
[Front End](https://kadkins4.github.io/TWiCS/#/tweets/new)
[Back End](https://twics.herokuapp.com/tweets.json)

**Comment by AndyWhitley** [comment]
@kadkins4 @frewabebe @cwcox Really great job on this project. Please refer to the Pull Request on the project repo for feedback:
https://github.com/kadkins4/TWiCS/pull/10
👍
