### ISSUE TITLE
Group 5: Liz, Jonathan, Rami

### ISSUE THREAD

**Issue by lizardbird** [ga-dc/project3-gallery#78]
Museogram is an app that allows users to explore museum info, see artworks at each museum, and add reviews to each artwork.

Potential addl features: map integration, user up/down voting.

**Comment by lizardbird** [comment]
Project submission - we did it!

Repos
[Back End Repo](https://github.com/jdpolakoff/museogramBackEnd)
[Front End Repo](https://github.com/jdpolakoff/museogramFrontEnd)

Deployed
[Front End](https://jdpolakoff.github.io/museogramFrontEnd)

**Comment by juancgarcia** [comment]
Great job team! Please refer to the Pull Request on your project repositories for feedback:
https://github.com/jdpolakoff/museogramFrontEnd/pull/1 (main `feedback.md` here)
https://github.com/jdpolakoff/museogramBackEnd/pull/3
👍 
@lizardbird @jdpolakoff @ramiGA
