### ISSUE TITLE
Group 4 Alex, Colleen, Mitche

### ISSUE THREAD

**Issue by mitcheguevara** [ga-dc/project3-gallery#79]
Twitter - Picture

**Comment by mitcheguevara** [comment]
Input String 
Randomize Letter 
Match String to Images 
Post Images

**Comment by mitcheguevara** [comment]
Rails App- https://github.com/mitcheguevara/Group4Project3
Angular App- https://github.com/mitcheguevara/Group4Angular-/tree/gh-pages
Website- https://mitcheguevara.github.io/Group4Angular-/#/

**Comment by AndyWhitley** [comment]
@mitcheguevara @colleeno @awandres Really excellent work on this project guys. Please refer to my PR on the project repo for feedback. 
https://github.com/mitcheguevara/Group4Angular-/pull/4
👍
