### ISSUE TITLE
Project3: Aaliyah, Diona, Drew, Max

### ISSUE THREAD

**Issue by dionadk** [ga-dc/project3-gallery#83]
react-front-end: https://oppnheimer.github.io/project3-front/
express-back-end:           https://ga-aha.herokuapp.com/

Group Members: Aaliyah, Diona, Drew, Max

**Comment by aspittel** [comment]
🎉  Great job! Feedback https://github.com/OppNHeimer/project3-front/pull/13/files https://github.com/OppNHeimer/project3-back/pull/1/files
