### ISSUE TITLE
SocialFit - Project 3 Jared Taylor, Casey Jordan, Ross Davis

### ISSUE THREAD

**Issue by rossjdavis** [ga-dc/project3-gallery#86]
https://github.com/rossjdavis/p3-backend-api

https://github.com/caseymjordan11/p3-front-end

https://socialfit-api.herokuapp.com/api/12-15-2017

http://social-fit.surge.sh

**Comment by AndyWhitley** [comment]
Please refer to the Pull Request on each repo above for feedback:

Front End: https://github.com/caseymjordan11/p3-front-end/pull/5
Back End: https://github.com/rossjdavis/p3-backend-api/pull/1

👍
