### ISSUE TITLE
LearnNGrow (Meg, Stella, Charles)

### ISSUE THREAD

**Issue by megmaciver13** [ga-dc/project3-gallery#89]
Back End Deployment: https://kids-app-back-end.herokuapp.com/
Front End Deployment: http://learn-n-grow.surge.sh/

Back End Repo: https://github.com/megmaciver13/kids-app-back-end
Front End Repo: https://github.com/megmaciver13/kids-app-front-end

By: Meg MacIver, Stella Gordon-Zigel, Charles Wilner

**Comment by perryf** [comment]
👍 Great work everyone! 👍 
👍 Check out my pull request on each repo for feedback 👍 

Front End: https://github.com/megmaciver13/kids-app-front-end/pull/27
Back End: https://github.com/megmaciver13/kids-app-back-end/pull/16
