### ISSUE TITLE
You suck at art (Steven Farris Jack)

### ISSUE THREAD

**Issue by StevenC53** [ga-dc/project3-gallery#90]
Front end repo: https://github.com/FarrisIsmati/telestrations_online
Back end repo: https://github.com/StevenC53/telestrations_online_back_end

Front end deployment: yousuckatart.surge.sh
Back end deployment: https://project3-sjf.herokuapp.com/

**Comment by AndyWhitley** [comment]
Please refer to the pull requests on the project's repos for feedback:
- Back End: https://github.com/StevenC53/telestrations_online_back_end/pull/4
- Front End: https://github.com/FarrisIsmati/telestrations_online/pull/23

👍
