### ISSUE TITLE
Lord Bless Project 3 (Kevon, Ryan, Annette, Devon)

### ISSUE THREAD

**Issue by keaglin** [ga-dc/project3-gallery#92]
LitSwap!

**Frontend/UI**
Repo: https://github.com/keaglin/project3-react
Deployed: https://build-ummoipeyau.now.sh/

**Backend/API**
Repo: https://github.com/keaglin/project3-api
Deployed: http://lit-swap.herokuapp.com/books

**Comment by blankol** [comment]
Deployment Update 2/2/18:
[LitSwap Frontend/UI](http://cynical-cracker.surge.sh/)
