### ISSUE TITLE
Project3: ToDoDos - Brian, Neechie, Zola, Temicka

### ISSUE THREAD

**Issue by findyourneechie** [ga-dc/project3-gallery#95]
[FrontEnd Repo](https://github.com/BrownSugarMama/Project3_MERN_TaskList_FrontEnd)
[Backend Repo](https://github.com/BrownSugarMama/Project3_MERN_TaskList_BackEnd)
[Deployed App](http://dangerous-chain.surge.sh/)

**Comment by aspittel** [comment]
Awesome job! Feedback: https://github.com/BrownSugarMama/Project3_MERN_TaskList_FrontEnd/pull/1/files and https://github.com/BrownSugarMama/Project3_MERN_TaskList_BackEnd/pull/2/files
